"use client";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Dumbbell, Users, Trophy, Brain, Zap, Heart } from "lucide-react";
import Link from "next/link";

const features = [
    {
        icon: Brain,
        title: "AI-Powered Training",
        description: "Get personalized workout plans generated by our intelligent AI trainer system",
        link: "/exercise-recommender",
        linkText: "Try AI Trainer"
    },
    {
        icon: Dumbbell,
        title: "Modern Gym Equipments",
        description: "Browse our extensive collection of latest fitness equipment and technology",
        link: "/equipments",
        linkText: "View Equipment"
    },
    {
        icon: Users,
        title: "Expert Trainers",
        description: "Certified professionals to guide your fitness journey with specialized programs",
        link: "/membership",
        linkText: "Get Started"
    },
    {
        icon: Heart,
        title: "Specialized Care",
        description: "Dedicated programs for pregnant women and disabled individuals with expert support",
        link: "/membership",
        linkText: "Learn More"
    },
    {
        icon: Trophy,
        title: "Proven Results",
        description: "Track your progress with our comprehensive analytics and achievement system",
        link: "/dashboard",
        linkText: "Track Progress"
    },
    {
        icon: Zap,
        title: "Premium Experience",
        description: "Access exclusive features, nutrition plans, and priority trainer consultations",
        link: "/membership",
        linkText: "Go Premium"
    },
];

export default function FeaturesSection() {
    return (
        <section id="features" className="py-20 bg-muted/30 relative">
            <div className="absolute inset-0 bg-gradient-to-r from-transparent via-primary/5 to-transparent"></div>
            <div className="main-container mx-auto px-4 sm:px-6 lg:px-8 relative">
                <div className="text-center space-y-4 mb-16">
                    <h2 className="text-3xl sm:text-4xl lg:text-5xl font-outfit font-bold text-primary-text">
                        Why Choose FitSphere?
                    </h2>
                    <p className="text-lg sm:text-xl text-sub-text font-lato max-w-3xl mx-auto">
                        Experience the difference with our premium facilities and comprehensive fitness ecosystem
                    </p>
                </div>
                <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8">
                    {features.map((feature, index) => (
                        <Card
                            key={index}
                            className="text-center border-border/50 shadow-xl bg-card/80 backdrop-blur-sm hover:shadow-2xl hover:shadow-primary/10 transition-all duration-500 transform hover:scale-105 group cursor-pointer">
                            <CardHeader className="pb-4">
                                <div className="mx-auto w-16 h-16 bg-black-primary rounded-2xl flex items-center justify-center mb-6 group-hover:from-primary/30 group-hover:to-primary/20 transition-all duration-300">
                                    <feature.icon className="h-8 w-8 text-green-primary group-hover:scale-110 transition-transform duration-300" />
                                </div>
                                <CardTitle className="text-xl sm:text-2xl font-outfit">{feature.title}</CardTitle>
                            </CardHeader>
                            <CardContent className="space-y-4">
                                <p className="text-sub-text text-sm font-lato sm:text-base">{feature.description}</p>
                                <Link href={feature.link}>
                                    <Button 
                                        variant="outline" 
                                        size="sm"
                                        className="w-full group-hover:bg-primary group-hover:text-primary-foreground transition-colors duration-300"
                                    >
                                        {feature.linkText}
                                    </Button>
                                </Link>
                            </CardContent>
                        </Card>
                    ))}
                </div>
            </div>
        </section>
    );
}
